### ISSUE TITLE
RavePaymentDataEncryption package not hosted on nugget.

### ISSUE THREAD

**Issue by toksdotdev** [TadeSamson/RavePaymentDataEncryption#2]
I've searched nugget for this package, and I was unable to find it. 

Also, no directions on how to install the package.

I know I could just use the source code from the project, but since the project Readme.md stated that it's a nugget package, then its advice-able to make it a package(if it isn't).

**Comment by tadesamson** [comment]
So, sorry this is coming late @TNkemdilim .  The use of the word nugget is contextual here. I mean "a small chunk of code". I didn't mean this is available as a nugget package. I'll try and make it one soon though. Thanks.

**Comment by toksdotdev** [comment]
Ok then...
